# from a ubuntu with mysql
FROM hseeberger/scala-sbt

###########################################back end
RUN mkdir /scalatraBackend 
COPY ScalatraSlick.jar /scalatraBackend/

CMD ["java", "-jar", "/scalatraBackend/ScalatraSlick.jar"]


###########################################front end



