version: '3'
services:
  mysql:
    image: mysql:5.6.26
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
  dockerapp:
     image: marathonfan/scalatrabackend
     build: .
     ports: 
      - "8080:8080"
      - "4200:4200"
     tty: true
     depends_on:
      - mysql




